---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-mon
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-mon
  template:
    metadata:
      labels:
        app: nginx-mon
    spec:
      containers:
      - name: nginx-mon
        image: brdm88/nginx-mon:0.1
        resources:
          limits:
            memory: "128Mi"
            cpu: "100m"
        ports:
        - name: web
          containerPort: 8080
      - name: nginx-exporter
        image: nginx/nginx-prometheus-exporter:0.8.0
        args: ['-nginx.scrape-uri', 'http://localhost:8080/basic_status']
        resources:
          limits:
            memory: "128Mi"
            cpu: "100m"
        ports:
        - name: metrics
          containerPort: 9113
