apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: nginx-mon
  labels:
    app: nginx-mon
spec:
  selector:
    matchLabels:
      app: nginx-mon
  endpoints:
  - port: metrics
    path: '/metrics'