apiVersion: v1
kind: Pod
metadata:
  labels:
    run: frontend
  name: frontend
spec:
  containers:
  - image: brdm88/hipshop-frontend:0.0.1
    name: frontend
    resources:
      limits:
        memory: "256Mi"
        cpu: "500m"
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
